modLoader="javafml"
loaderVersion="[47,48)"
license="MIT"
issueTrackerURL="https://github.com/n624-dev/internal-furnace/issues"

[[mods]]
modId="internal_furnace"
version="${file.jarVersion}"
displayName="Internal Furnace"
authors="n624-dev"
displayURL="https://github.com/n624-dev/internal-furnace"
description='''A player-owned, upgradeable furnace with server-authoritative recipes, heat, storage and automation.'''

[[dependencies.internal_furnace]]
modId="forge"
mandatory=true
versionRange="[47.4.10]"
ordering="NONE"
side="BOTH"

[[dependencies.internal_furnace]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.internal_furnace]]
modId="mmorpg"
mandatory=true
versionRange="[6.4.7]"
ordering="AFTER"
side="BOTH"

[[dependencies.internal_furnace]]
modId="library_of_exile"
mandatory=true
versionRange="[2.1.11]"
ordering="AFTER"
side="BOTH"

[[dependencies.internal_furnace]]
modId="mowziesmobs"
mandatory=true
versionRange="[1.8.2]"
ordering="AFTER"
side="BOTH"
